version: '3.8'

services:
  lifeskill-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lifeskill-app:v1.0.0 # Ubah versi ini (misal ke v1.0.1, v1.0.2) untuk memaksa Portainer build ulang
    container_name: lifeskill_app
    restart: always
    ports:
      - "8092:3000"
    volumes:
      - lifeskill_data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=super_secret_jwt_key_lifeskill_2026

volumes:
  lifeskill_data:
